name: bloc_architecture
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: 4.0.6

  # Responsive
  flutter_screenutil: 5.5.4

  # State Management + equipment
  bloc: 8.1.0
  flutter_bloc: 8.1.1
  equatable: ^2.0.5

  # Image
  cached_network_image: ^3.2.2


  # Cupertino
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.otf
        - asset: assets/fonts/Proxima-Nova-Thin.otf
          weight: 100
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-Extrabold.otf
          weight: 800
        - asset: assets/fonts/Proxima-Nova-Black.otf
          weight: 900
